version: '3.8'

services:
  web:
    build: .
    # Pass the production environment file
    env_file:
      - .env.prod
    ports:
      - "127.0.0.1:8000:8000"
    # This command collects static files, runs migrations, and then starts gunicorn
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn food_delivery.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - media_data:/app/media
      - ./staticfiles:/app/staticfiles

volumes:
  media_data:
