# Generated by Django on 2026-07-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivender', '0002_vendor_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDistanceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_distance', models.PositiveIntegerField(help_text='H3 grid distance (0 for same tile, 1 for adjacent, etc.)', unique=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderlocation',
            name='h3_index',
            field=models.CharField(blank=True, help_text='H3 spatial index (Resolution 7)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='h3_index',
            field=models.CharField(blank=True, help_text='H3 spatial index (Resolution 7)', max_length=15, null=True),
        ),
    ]
